### ISSUE TITLE
一点关于修改的讨论

### ISSUE THREAD

**Issue by Ladbaby** [dada878/LimeStartPlus#2]
首先感谢分享关于模仿青柠起始页的实现，这是我暂时能找到的风格上最接近的仓库。我基于这些代码做了些许修改，希望在这里分享一下，仅仅作为讨论意义。

- 在 `searchSuggestion.vue` 里，`watch` 部分里存在一个对prop `show` 的监视。这个监视的作用似乎是在 `<input>` 元素被聚焦且输入的内容不为空的时候，展示搜索建议。但是这么做似乎会导致一个小问题：在用户输入的内容发生**一次**改变的时候，会触发**两次** `getSuggests` 函数。我尝试将该处对 `show` 的监视注释掉，就只会变成触发一次函数调用，而且似乎也能达到“元素被聚焦且输入的内容不为空的时候，展示搜索建议”的目的
- 对输入框做了节流，让`getSuggests`函数不会过度频繁地被调用

因为怕搜索建议的获取发送过于频繁导致被对面服务器禁了，所以做了上述改动，仅供参考。

**Comment by dada878** [comment]
非常感謝大佬的建議與支持
如果有興趣的話可以直接發 PR 哦
不過我近期大多在忙一些其他專案和事情
比較沒什麼時間來維護這個專案
未來有機會再來做這部分的修改

**Comment by Ladbaby** [comment]
没事没事，我也只是分享一下思路😂
